# Generated by Django 4.2.1 on 2023-05-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
